local _, ns = ...
local Misc = ns.Misc

Filger_Theme = {
    ['player_buff_icon'] = {
        Name = "P_BUFF_ICON",
        Direction = "LEFT",
        Mode = "ICON",
        Interval = Misc.Interval,
        Alpha = 1,
        IconSize = Misc.IconSize,
        Position = {unpack(FilgerPositions.player_buff_icon)},
    },
    ['player_proc_icon'] = {
        Name = "P_PROC_ICON",
        Direction = "RIGHT",
        Mode = "ICON",
        Interval = Misc.Interval,
        Alpha = 1,
        IconSize = Misc.IconSize,
        Position = {unpack(FilgerPositions.player_proc_icon)},
    },
    ['special_proc_icon'] = {
        Name = "SPECIAL_P_BUFF_ICON",
        Direction = "LEFT",
        Mode = "ICON",
        Interval = Misc.Interval,
        Alpha = 1,
        IconSize = Misc.IconSize,
        Position = {unpack(FilgerPositions.special_proc_icon)},
    },
    ['target_debuff_icon'] = {
        Name = "T_DEBUFF_ICON",
        Direction = "RIGHT",
        Mode = "ICON",
        Interval = Misc.Interval,
        Alpha = 1,
        IconSize = Misc.IconSize,
        Position = {unpack(FilgerPositions.target_debuff_icon)},
    },
    ['target_buff_icon'] = {
        Name = "T_BUFF",
        Direction = "UP",
        Mode = "ICON",
        Interval = Misc.Interval,
        Alpha = 1,
        IconSize = Misc.BigIconSize,
        Position = {unpack(FilgerPositions.target_buff_icon)},
    },
    ['pve_debuff'] = {
        Name = "PVE/PVP_DEBUFF",
        Direction = "UP",
        Mode = "ICON",
        Interval = Misc.Interval,
        Alpha = 1,
        IconSize = Misc.BigIconSize,
        Position = {unpack(FilgerPositions.pve_debuff)},
    },
    ['pve_cc'] = {
        Name = "PVE/PVP_CC",
        enable = Misc.Pbar,
        Direction = "DOWN",
        IconSide = "LEFT",
        Mode = "BAR",
        Interval = Misc.Interval,
        Alpha = 1,
        IconSize = Misc.barIconSize,
        BarWidth = Misc.barw,
        Position = {unpack(FilgerPositions.pve_cc)},
    },
    ['cooldown'] = {
        Name = "COOLDOWN",
        enable = Misc.CD,
        Direction = "RIGHT",
        Mode = "ICON",
        NumPerLine = Misc.CDnum,
        Interval = Misc.Interval,
        Alpha = 1,
        IconSize = Misc.CDIconSize,
        Position = {unpack(FilgerPositions.cooldown)},
    },
    ['target_bar'] = {
        Name = "T_DE/BUFF_BAR",
        enable = Misc.Tbar,
        Direction = "UP",
        IconSide = "LEFT",
        Mode = "BAR",
        Interval = Misc.Interval,
        Alpha = 1,
        IconSize = Misc.barIconSize,
        BarWidth = Misc.barw,
        Position = {unpack(FilgerPositions.target_bar)},
    },
}